openapi: 3.0.0
info:
  title: API's OpenData do Open Banking Brasil
  description: As API's descritas neste documento são referentes as API's da fase OpenData do Open Banking Brasil.
  version: 1.0.0
servers:
  - url: http://api.banco.com.br/open-banking
paths:
  /channels/v1/banking-agents:
    get:
      tags:
      - "Channels"
      summary: Obtém a lista de dependências próprias da instituição financeira.
      responses:
        '200':
          description: Uma instituição financeira contendo sua lista de dependências próprias.
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ResponseBankingAgentsList'
  /channels/v1/branches:
    get:
      tags:
      - "Channels"
      summary: Obtém a lista de dependências próprias da instituição financeira.
      responses:
        '200':
          description: Uma instituição financeira contendo sua lista de dependências próprias.
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ResponseBranchesList'
  /channels/v1/electronic-channels:
    get:
      tags:
      - "Channels"
      summary: Obtém a lista de canais eletrônicos de atendimento da instituição financeira.
      responses:
        '200':
          description: Uma instituição financeira contendo sua lista de canais eletrônicos de atendimento.
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ResponseEletronicChannelsList'
components:
  schemas:
    ResponseBankingAgentsList:
      type: object
      required:
        - data
        - links
        - meta
      properties:
        data:
          type: object
          required:
            - organisation
          properties:
            organisation:
              type: array
              items:
                $ref: '#/components/schemas/BankingAgentsOrganisation'
              description: Lista das organizaçõs titulares das dependências
        links:
          $ref: '#/components/schemas/Links'
        meta:
          $ref: '#/components/schemas/Meta'
      example:
        data:
          organisation:
            - name: Big Banks
              contractors:
                - name: Brazil Contractor LTDA
                  cnpjMainNumber: '14684579'
                  cnpjSubsidiaryNumber: '1'
                  cnpjCheckNumber: '63'
                  bankingAgents:
                    - identification:
                        corporationName: Salt Mount S/A
                        groupName: HyperMarkets
                        tradingName: SmallMarket Express
                        cnpjMainNumber: '50870366'
                        cnpjSubsidiaryNumber: '1'
                        cnpjCheckNumber: '90'
                      postalAddress:
                        streetTypeName: Alameda
                        streetName: Santos
                        buildingNumber: '1041'
                        additionalInfoText: null
                        districtName: Cerqueira César
                        townName: São Paulo
                        countrySubDivisionCode: SP
                        postCode: 01419-002
                      services:
                        codes:
                          - '1'
                          - '2'
                        detailText: null
        links:
          self: 'https://api.banco.com.br/open-banking/channels/v1/banking-agents'
          first: 'https://api.banco.com.br/open-banking/channels/v1/banking-agents'
          prev: null
          next: null
          last: 'https://api.banco.com.br/open-banking/channels/v1/banking-agents'
        meta:
          totalRecords: 1
          totalPages: 1
    BankingAgentsOrganisation:
      type: object
      required:
        - name
        - contractors
      properties:
        name:
          type: string
          description: Nome do conglomerado proprietário da dependência (titular).
        contractors:
          type: array
          items:
            $ref: '#/components/schemas/BankingAgentsContractor'
          description: Lista de contratantes  
    BankingAgentsContractor:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        bankingAgents:
          type: array
          items:
            $ref: '#/components/schemas/BankingAgent'
      allOf:
        - $ref: '#/components/schemas/CNPJ'
    ResponseBranchesList:
      type: object
      required:
      - data
      - links
      - meta
      properties:
        data:
          type: object
          required:
            - organisation
          properties:
            organisation:
              type: array
              items:
                $ref: '#/components/schemas/BranchesOrganisation'
              description: Lista das organizaçõs titulares das dependências
        links:
          $ref: '#/components/schemas/Links'
        meta:
          $ref: '#/components/schemas/Meta'
      example:
        data:
          organization:
            - name: string
              companies:
                - name: string
                  cnpjMainNumber: string
                  cnpjSubsidiaryNumber: string
                  cnpjCheckNumber: string
                  branches:
                    - identification:
                        typeNumber: string
                        identificationCode: string
                        checkDigitNumber: string
                        name: string
                      postalAddress:
                        streetTypeName: string
                        streetName: string
                        buildingNumber: string
                        additionalInfoText: string
                        districtName: string
                        townName: string
                        countrySubDivisionCode: string
                        postCode: string
                      availability:
                        standard:
                          - weekdayName: string
                            openingTime: string
                            closingTime: string
                        exceptionAvailabilityText: string
                        publicAccessFlag: string
                        phones:
                          - typeCode: string
                            dddCode: string
                            number: string
                      services:
                        codes:
                          - string
                        detailText: string
        links:
          self: string
          first: string
          prev: string
          next: string
          last: string
        meta:
          totalRecords: integer
          totalPages: integer
    BranchesOrganisation:
      type: object
      required:
        - name
        - companies
      properties:
        name:
          type: string
          description: Nome do conglomerado proprietário da dependência (titular).
        companies:
          type: array
          items:
            $ref: '#/components/schemas/BranchesCompanies'
          description: Lista de contratantes  
    BranchesCompanies:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        bankingAgents:
          type: array
          items:
            $ref: '#/components/schemas/Branch'
      allOf:
        - $ref: '#/components/schemas/CNPJ'
    ResponseEletronicChannelsList:
      type: object
      required:
      - data
      - links
      - meta
      properties:
        data:
          type: object
          required:
            - organisation
          properties:
            organisation:
              type: array
              items:
                $ref: '#/components/schemas/EletronicChannelsOrganisation'
              description: Lista das organizações titulares das dependências
        links:
          $ref: '#/components/schemas/Links'
        meta:
          $ref: '#/components/schemas/Meta'
      example:
        data:
          organisation:
            - name: The Big Bank Company
              channels:
                - identification:
                    typeCode: '4'
                    phones:
                      - ddiCode: null
                        dddCode: null
                        number: 0800 555 1234
                        descriptionText: Para regiões metropolitanas e capitais usar o telefone
                      - ddiCode: null
                        dddCode: '11'
                        number: 4004-4828
                        descriptionText: Demais localidades
                      - ddiCode: '55'
                        dddCode: '11'
                        number: 44003-4820
                        descriptionText: Para clientes no exterior
                  services:
                    codes:
                      - '1'
                      - '2'
                      - '3'
                    detailText: null
                - identification:
                    typeCode: '1'
                    urlName: 'https://thebigbankcompany.sample.com'
                  services:
                    codes:
                      - '1'
                      - '2'
                      - '3'
                      - '4'
                      - '6'
                      - '7'
                    detailText: Canal de atendimento 2
          links:
            self: 'https://api.banco.com.br/open-banking/channels/v1/electronic-channels'
            first: 'https://api.banco.com.br/open-banking/channels/v1/electronic-channels'
            prev: null
            next: null
            last: 'https://api.banco.com.br/open-banking/channels/v1/electronic-channels'
          meta:
            totalRecords: 1
            totalPages: 1
    EletronicChannelsOrganisation:
      type: object
      required:
        - name
        - channels
      properties:
        name:
          type: string
          description: Nome do conglomerado proprietário da dependência (titular).
        channels:
          type: array
          items:
            $ref: '#/components/schemas/EletronicChannel'
          description: Lista  de canais de atendimento eltrônico
    BankingAgent:
      type: object
      required:
        - identification
        - postalAddress
        - services
      properties:
        identification:
          $ref: '#/components/schemas/BankingAgentIdentification'
        postalAddress:
          $ref: '#/components/schemas/PostalAddress'
        services:
          $ref: '#/components/schemas/BankingAgentServices'
    BankingAgentIdentification:
      type: object
      properties:
        corporationName:
          type: string
          maxLength: 100
        groupName:
          type: string
          maxLength: 100
        tradingName:
          type: string
          maxLength: 100
      allOf:
        - $ref: '#/components/schemas/CNPJ'
      required:
        - corporationName
    BankingAgentServices:
      type: object
      properties:
        codes:
          type: array
          items:
            type: string
            enum: ["1","2","3","4","5","6","7","8"]
            maxLength: 2
            pattern: ^\d{1,2}$
            description: >
              Serviços oferecidos pelo correspondente bancário
              * `1` - Recepção e encaminhamento de propostas de abertura de contas
              * `2` - Realização de recebimentos, pagamentos e transferências eletrônicas
              * `3` - Recebimentos e pagamentos de qualquer natureza
              * `4` - Execução ativa e passiva de ordens de pagamento
              * `5` - Recepção e encaminhamento de propostas de operações de crédito e de arrendamento mercantil
              * `6` - Recebimento e pagamentos relacionados a letras de câmbio de aceite da instituição
              * `7` - Recepção e encaminhamento de propostas de fornecimento de cartões de crédito
              * `8` - Realização de operações de câmbio
          description: Serviços oferecidos pelo canal eletrônico
        detailText:
          type: string
          maxLength: 2000
          description: Campo aberto para detalhamento
      required:
        - codes
    Branch:
      type: object
      required:
        - identification
        - postalAddress
        - services
        - availability
      properties:
        identification:
            $ref: '#/components/schemas/BranchIdentification'
        postalAddress:
            $ref: '#/components/schemas/PostalAddress'
        availability:
            $ref: '#/components/schemas/BranchAvailability'
        services:
            $ref: '#/components/schemas/BranchServices'
    BranchIdentification:
      type: object
      properties:
        typeNumber:
          type: string
          enum: ["1","2","3"]
          maxLength: 2
          pattern: ^\d{1,2}$
          description: > 
            Tipo de dependência física
            * `1` - Agência
            * `2` - Posto de Atendimento
            * `3` - Posto de Atendimento Eletrônico 
        identificationCode:
          type: string
          maxLength: 4
          pattern: ^\d{4}$
        checkDigitNumber:
          type: string
          maxLength: 1
          pattern: ^\d{1}$
        name:
          type: string
          maxLength: 100
      required:
        - type
        - identification
        - name
    BranchAvailability:
      type: object
      properties:
        standard:
          type: array
          items:
            properties:
              weekdayName:
                type: string
                enum: ["Domingo","Segunda-feira","Terça-feira","Quarta-feira","Quinta-feira","Sexta-feira","Sábado"]
                description: Dia da semana de abertura da dependência bancária
                maxLength: 13
              openingTime:
                type: string
                description: Horário de abertura da dependência bancária (UTC)
                maxLength: 13
                pattern: ^([0|1|2]{1})([0-9]{1}):([0|1|2|3|4|5]{1})([0-9]{1}):([0|1|2|3|4|5]{1})([0-9]{1})\+([0-9]{4})$
              closingTime:
                type: string
                description: Horário de fechamento da dependência bancária (UTC)
                maxLength: 13
                pattern: ^([0|1|2]{1})([0-9]{1}):([0|1|2|3|4|5]{1})([0-9]{1}):([0|1|2|3|4|5]{1})([0-9]{1})\+([0-9]{4})$
            required:
              - weekday
              - openingTime
              - closingTime
        exceptionAvailabilityText:
          type: string
          maxLength: 2000
        publicAccessFlag:
          type: boolean
          enum: [true,false]
        phones:
          type: array
          items:
            properties:
              typeCode:
                type: string
                maxLength: 1
                pattern: ^\d{1}$
                description: >
                  Tipo de Telefone
                  * `1` - Fixo
                  * `2` - Móvel
              dddCode:
                type: string
                maxLength: 2
                pattern: ^\d{2}$
              number:
                type: string
                maxLength: 10
                pattern: ^([0-9]{4,5})-([0-9]{4})$
          description: Telefone
      required:
        - standard
        - exceptionAvailability
        - publicAccessFlag
    BranchServices:
      type: object
      properties:
        codes:
          type: array
          items:
            type: string
            enum: ["1","2","3","4","5","6","7","8"]
            maxLength: 2
            pattern: ^\d{1,2}$
          description: > 
            Serviços oferecidos pela dependência própria
            * `1` - Abertura de contas
            * `2` - Recebimentos, pagamentos e transferências eletrônicas
            * `3` - Recebimentos e pagamentos de qualquer natureza
            * `4` - Operações de crédito
            * `5` - Cartão de crédito
            * `6` - Operações de câmbio
            * `7` - Investimentos
            * `8` - Seguros
        detailText:
          type: string
          description: Campo aberto para detalhamento
          maxLength: 2000
      required:
        - codes
    EletronicChannel:
      type: object
      properties:
        identification:
          $ref: '#/components/schemas/EletronicChannelIdentification'
        services:
          $ref: '#/components/schemas/EletronicChannelServices'
      required:
        - identification
        - services
    EletronicChannelIdentification:
      type: object
      required:
        - typeCode
      properties:
        typeCode:
          type: string
          enum: ["1","2","3","4","5","6"]
          maxLength: 2
          pattern: ^\d{1,2}$
          description: >
            Tipo de canal de atendimento eletrônico
            * `1` - Internet banking
            * `2` - Mobile banking
            * `3` - Central telefônica banking
            * `4` - SAC
            * `5` - Ouvidoria
            * `6` - Chat
        phones:
          type: array
          items:
            properties:
              ddiCode:
                type: string
                maxLength: 2
                pattern: ^\d{2}$
              dddCode:
                type: string
                maxLength: 2
                pattern: ^\d{2}$
              number:
                type: string
                maxLength: 13
                pattern: ^([0-9]{4,5})-([0-9]{4})$
              descriptionText:
                type: string
                maxLength: 50
        urlName:
          type: string
          maxLength: 1024
    EletronicChannelServices:
      type: object
      required:
        - codes
      properties:
        codes:
          type: array
          items:
            type: string
            enum: ["1","2","3","4","5","6","7","8"]
            maxLength: 2
            pattern: ^\d{1,2}$
            description: >
              Serviços oferecidos pelo canal de atendimento eletrônico
              * `1` - Abertura de contas
              * `2` - Recebimentos, pagamentos e transferências eletrônicas
              * `3` - Operações de crédito
              * `4` - Cartão de crédito
              * `5` - Operações de câmbio
              * `6` - Investimentos
              * `7` - Seguros
              * `8` - Atendimento as demandas de cliente
        detailText:
          type: string
          maxLength: 2000
          description: Campo aberto para detalhamento
    PostalAddress:
      type: object
      properties:
        streetTypeName:
          type: string
          description: Tipo de logradouro
          maxLength: 10
          enum: ["Aeroporto", "Alameda", "Área", "Avenida", "Campo", "Chácara", "Colônia", "Condomínio", "Conjunto", "Distrito", "Esplanada", "Estação", "Estrada", "Fazenda", "Feira", "Jardim", "Ladeira", "Lago", "Lagoa", "Largo", "Loteamento", "Núcleo", "Parque", "Passarela", "Pátio", "Praça", "Quadra", "Recanto", "Residencial", "Rodovia", "Rua", "Setor", "Sítio", "Travessa", "Trecho", "Trevo", "Vale", "Vereda", "Via", "Viaduto", "Viela", "Vila"]
        streetName:
          type: string
          description: Nome do logradouro
          maxLength: 50
        buildingNumber:
          type: string
          description: Número
          maxLength: 6
        additionalInfoText:
          type: string
          description: Complemento
          maxLength: 30
        districtName:
          type: string
          description: Bairro
          maxLength: 50
        townName:
          type: string
          description: Cidade
          maxLength: 50
        countrySubDivisionCode:
          type: string
          description: Estado
          pattern: ^[A-Z]{2}$
          enum: [AC,AL,AP,AM,BA,CE,DF,ES,GO,MA,MT,MS,MG,PA,PB,PR,PE,PI,RJ,RN,RS,RO,RR,SC,SP,SE,TO]
          maxLength: 2
        postCode:
          type: string
          description: CEP
          pattern: ^\d{5}-\d{3}$
          maxLength: 9
      required: 
        - streetType
        - streetName
        - buildingNumber
        - district
        - townName
        - countrySubDivision
        - postCode
    CNPJ:
      type: object
      properties:
        cnpjMainNumber:
          type: string
          description: Raíz do CNPJ
          pattern: ^\d{2}.\d{3}.\d{3}$
          maxLength: 10
        cnpjSubsidiaryNumber:
          type: string
          description: Filial do CNPJ
          pattern: ^\d{4}$
          maxLength: 4
        cnpjCheckNumber:
          type: string
          description: Dígitos de verificação do CNPJ
          pattern: ^\d{2}$
          maxLength: 2
      required:
        - cnpjMain
        - cnpjSubsidiary
        - cnpjCheckNumber 
    Links:
      type: object
      properties:
        self:
          type: string
          description: URL da página atualmente requisitada
        first:
          type: string
          description: URL da primeira página de registros
        prev:
          type: string
          description: URL da página anterior de registros
        next:
          type: string
          description: URL da próxima página de registros
        last:
          type: string
          description: URL da última página de registros
    Meta:
      type: object
      properties:
        totalRecords:
          type: integer
          description: Total de registros encontrados
        totalPages:
          type: integer
          description: Total de páginas para os registros encontrados
      required:
        - totalRecords
        - totalPages