openapi: 3.0.0
info:
  title: API's OpenData do Open Banking Brasil
  description: As API's descritas neste documento são referentes as API's da fase OpenData do Open Banking Brasil.
  version: 1.0.0
servers:
  - url: http://api.banco.com.br/open-banking
paths:
  /channels/v1/banking-agents:
    get:
      tags:
      - "Channels"
      summary: Obtém a lista de dependências próprias da instituição financeira.
      responses:
        '200':
          description: Uma instituição financeira contendo sua lista de dependências próprias.
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ResponseBankingAgentsList'
  /channels/v1/branches:
    get:
      tags:
      - "Channels"
      summary: Obtém a lista de dependências próprias da instituição financeira.
      responses:
        '200':
          description: Uma instituição financeira contendo sua lista de dependências próprias.
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ResponseBranchesList'
  /channels/v1/electronic-channels:
    get:
      tags:
      - "Channels"
      summary: Obtém a lista de canais eletrônicos de atendimento da instituição financeira.
      responses:
        '200':
          description: Uma instituição financeira contendo sua lista de canais eletrônicos de atendimento.
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ResponseEletronicChannelsList'
components:
  schemas:
    ResponseBankingAgentsList:
      type: object
      required:
        - data
        - links
        - meta
      properties:
        data:
          type: object
          required:
            - organisation
          properties:
            organisation:
              type: array
              items:
                $ref: '#/components/schemas/BankingAgentsOrganisation'
              description: Lista das organizaçõs titulares das dependências
        links:
          $ref: '#/components/schemas/Links'
        meta:
          $ref: '#/components/schemas/Meta'
      example:
        data:
          organisation:
            - name: Big Banks
              companies:
                - name: Brazil Campany LTDA
                  cnpjNumber: '12345678901234'
                  contractors:
                    - name: Brazil Contractor LTDA
                      cnpjNumber: '14684579163'
                      bankingAgents:
                        - identification:
                            corporationName: Salt Mount S/A
                            groupName: HyperMarkets
                            cnpjNumber: '50870366190'
                          postalAddress:
                            streetType: Alameda
                            streetName: Santos
                            buildingNumber: '1041'
                            additionalInfo: null
                            districtName: Cerqueira César
                            townName: São Paulo
                            countrySubDivision: SP
                            postCode: 01419-002
                          services:
                            codes:
                              - '1'
                              - '2'
                            additionalInfo: null
        links:
          self: 'https://api.banco.com.br/open-banking/channels/v1/banking-agents'
          first: 'https://api.banco.com.br/open-banking/channels/v1/banking-agents'
          prev: null
          next: null
          last: 'https://api.banco.com.br/open-banking/channels/v1/banking-agents'
        meta:
          totalRecords: 1
          totalPages: 1
    BankingAgentsOrganisation:
      type: object
      required:
        - name
        - companies
      properties:
        name:
          type: string
          description: Nome do conglomerado proprietário da dependência (titular).
        companies:
          type: array
          items:
            $ref: '#/components/schemas/BankingAgentsCompanies'
          description: Lista de instituições pertencentes à organização  
    BankingAgentsCompanies:
      type: object
      required:
        - name
        - cnpjNumber
        - contractors
      properties:
        name:
          type: string
          description: Nome do conglomerado responsável pela contrataçao do Correspondente.
        contractors:
          type: array
          items:
            $ref: '#/components/schemas/BankingAgentsContractor'
          description: Lista de contratantes
      allOf:
        - $ref: '#/components/schemas/CNPJ'
    BankingAgentsContractor:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        bankingAgents:
          type: array
          items:
            $ref: '#/components/schemas/BankingAgent'
      allOf:
        - $ref: '#/components/schemas/CNPJ'
    ResponseBranchesList:
      type: object
      required:
      - data
      - links
      - meta
      properties:
        data:
          type: object
          required:
            - organisation
          properties:
            organisation:
              type: array
              items:
                $ref: '#/components/schemas/BranchesOrganisation'
              description: Lista das organizaçõs titulares das dependências
        links:
          $ref: '#/components/schemas/Links'
        meta:
          $ref: '#/components/schemas/Meta'
      example:
        data:
          organization:
            - name: The Big Bank Company
              companies:
                - name: RSR Bank
                  cnpjNumber: '14684579163'
                  branches:
                    - identification:
                        type: '1'
                        code: '7055'
                        checkDigit: '0'
                        name: Agência Alameda Santos
                      postalAddress:
                        streetType: Alameda
                        streetName: Santos
                        buildingNumber: '1041'
                        additionalInfo: null
                        districtName: Cerqueira César
                        townName: São Paulo
                        countrySubDivision: SP
                        postCode: 01419-002
                      availability:
                        standard:
                          - weekday: Segunda-feira
                            openingTime: '13:00:00+0000'
                            closingTime: '19:00:00+0000'
                          - weekday: Terça-feira
                            openingTime: '13:00:00+0000'
                            closingTime: '19:00:00+0000'
                          - weekday: Quarta-feira
                            openingTime: '13:00:00+0000'
                            closingTime: '19:00:00+0000'
                          - weekday: Quinta-feira
                            openingTime: '13:00:00+0000'
                            closingTime: '19:00:00+0000'
                          - weekday: Sexta-feira
                            openingTime: '13:00:00+0000'
                            closingTime: '19:00:00+0000'
                        exceptionAvailability: 'Exceto feriados municipais, estaduais e nacionais'
                        allowPublicAccess: 'true'
                        phones:
                          - type: '1'
                            areaCode: '11'
                            number: 4444-5555
                          - type: '2'
                            areaCode: '11'
                            number: 99999-8888
                      services:
                        codes:
                          - '1'
                          - '2'
                        additionalInfo: null
        links:
          self: 'https://api.banco.com.br/open-banking/channels/v1/branches'
          first: 'https://api.banco.com.br/open-banking/channels/v1/branches'
          prev: null
          next: null
          last: 'https://api.banco.com.br/open-banking/channels/v1/branches'
        meta:
          totalRecords: 1
          totalPages: 1
    BranchesOrganisation:
      type: object
      required:
        - name
        - companies
      properties:
        name:
          type: string
          description: Nome do conglomerado proprietário da dependência (titular).
        companies:
          type: array
          items:
            $ref: '#/components/schemas/BranchesCompanies'
          description: Lista de contratantes  
    BranchesCompanies:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        branches:
          type: array
          items:
            $ref: '#/components/schemas/Branch'
      allOf:
        - $ref: '#/components/schemas/CNPJ'
    ResponseEletronicChannelsList:
      type: object
      required:
      - data
      - links
      - meta
      properties:
        data:
          type: object
          required:
            - organisation
          properties:
            organisation:
              type: array
              items:
                $ref: '#/components/schemas/EletronicChannelsOrganisation'
              description: Lista das organizações titulares das dependências
        links:
          $ref: '#/components/schemas/Links'
        meta:
          $ref: '#/components/schemas/Meta'
      example:
        data:
          organisation:
            - name: The Big Bank Organisation
              companies:
                - name: The Big Bank Company
                  cnpjNumber: '12345678901234'
                  channels:
                    - identification:
                        type: '4'
                        phones:
                          - countryCode: null
                            areaCode: null
                            number: 0800 555 1234
                            additionalInfo: Para regiões metropolitanas e capitais usar o telefone
                          - countryCode: null
                            areaCode: '11'
                            number: 4004-4828
                            additionalInfo: Demais localidades
                          - countryCode: '55'
                            areaCode: '11'
                            number: 44003-4820
                            additionalInfo: Para clientes no exterior
                      services:
                        codes:
                          - '1'
                          - '2'
                          - '3'
                        additionalInfo: null
                    - identification:
                        type: '1'
                        url: 'https://thebigbankcompany.sample.com'
                      services:
                        codes:
                          - '1'
                          - '2'
                          - '3'
                          - '4'
                          - '6'
                          - '7'
                        additionalInfo: Canal de atendimento 2
        links:
          self: 'https://api.banco.com.br/open-banking/channels/v1/electronic-channels'
          first: 'https://api.banco.com.br/open-banking/channels/v1/electronic-channels'
          prev: null
          next: null
          last: 'https://api.banco.com.br/open-banking/channels/v1/electronic-channels'
        meta:
          totalRecords: 1
          totalPages: 1
    EletronicChannelsOrganisation:
      type: object
      required:
        - name
        - companies
      properties:
        name:
          type: string
          description: Nome do conglomerado proprietário da dependência (titular).
        companies:
          type: array
          items:
            $ref: '#/components/schemas/EletronicChannelsCompanies'
          description: Lista de instituições pertencentes à organização
    EletronicChannelsCompanies:
      type: object
      required:
        - name
        - channels
      properties:
        name:
          type: string
          description: Nome do conglomerado proprietário da dependência (titular).
        channels:
          type: array
          items:
            $ref: '#/components/schemas/EletronicChannel'
          description: Lista  de canais de atendimento eltrônico
      allOf:
        - $ref: '#/components/schemas/CNPJ'
    BankingAgent:
      type: object
      required:
        - identification
        - postalAddress
        - services
      properties:
        identification:
          $ref: '#/components/schemas/BankingAgentIdentification'
        postalAddress:
          $ref: '#/components/schemas/PostalAddress'
        services:
          $ref: '#/components/schemas/BankingAgentServices'
    BankingAgentIdentification:
      type: object
      properties:
        corporationName:
          type: string
          maxLength: 100
        groupName:
          type: string
          maxLength: 100
      allOf:
        - $ref: '#/components/schemas/CNPJ'
      required:
        - corporationName
    BankingAgentServices:
      type: object
      properties:
        codes:
          type: array
          items:
            type: string
            enum: ["1","2","3","4","5","6","7","8"]
            maxLength: 2
            pattern: ^\d{1,2}$
            description: >
              Serviços oferecidos pelo correspondente bancário
              * `1` - Recepção e encaminhamento de propostas de abertura de contas
              * `2` - Realização de recebimentos, pagamentos e transferências eletrônicas
              * `3` - Recebimentos e pagamentos de qualquer natureza
              * `4` - Execução ativa e passiva de ordens de pagamento
              * `5` - Recepção e encaminhamento de propostas de operações de crédito e de arrendamento mercantil
              * `6` - Recebimento e pagamentos relacionados a letras de câmbio de aceite da instituição
              * `7` - Recepção e encaminhamento de propostas de fornecimento de cartões de crédito
              * `8` - Realização de operações de câmbio
          description: Serviços oferecidos pelo canal eletrônico
        additionalInfo:
          type: string
          maxLength: 2000
          description: Campo aberto para detalhamento
      required:
        - codes
    Branch:
      type: object
      required:
        - identification
        - postalAddress
        - services
        - availability
      properties:
        identification:
            $ref: '#/components/schemas/BranchIdentification'
        postalAddress:
            $ref: '#/components/schemas/PostalAddress'
        availability:
            $ref: '#/components/schemas/BranchAvailability'
        services:
            $ref: '#/components/schemas/BranchServices'
    BranchIdentification:
      type: object
      properties:
        type:
          type: string
          enum: ["1","2","3"]
          maxLength: 2
          pattern: ^\d{1,2}$
          description: > 
            Tipo de dependência física
            * `1` - Agência
            * `2` - Posto de Atendimento
            * `3` - Posto de Atendimento Eletrônico 
        code:
          type: string
          maxLength: 4
          pattern: ^\d{4}$
        checkDigit:
          type: string
          maxLength: 1
          pattern: ^\d{1}$
        name:
          type: string
          maxLength: 100
      required:
        - type
        - code
        - checkDigit
        - name
    BranchAvailability:
      type: object
      properties:
        standard:
          type: array
          items:
            properties:
              weekday:
                type: string
                enum: ["Domingo","Segunda-feira","Terça-feira","Quarta-feira","Quinta-feira","Sexta-feira","Sábado"]
                description: Dia da semana de abertura da dependência bancária
                maxLength: 13
              openingTime:
                type: string
                description: Horário de abertura da dependência bancária (UTC)
                maxLength: 13
                pattern: ^([0|1|2]{1})([0-9]{1}):([0|1|2|3|4|5]{1})([0-9]{1}):([0|1|2|3|4|5]{1})([0-9]{1})\+([0-9]{4})$
              closingTime:
                type: string
                description: Horário de fechamento da dependência bancária (UTC)
                maxLength: 13
                pattern: ^([0|1|2]{1})([0-9]{1}):([0|1|2|3|4|5]{1})([0-9]{1}):([0|1|2|3|4|5]{1})([0-9]{1})\+([0-9]{4})$
            required:
              - weekday
              - openingTime
              - closingTime
        exceptionAvailability:
          type: string
          maxLength: 2000
        allowPublicAccess:
          type: boolean
          enum: [true,false]
        phones:
          type: array
          items:
            properties:
              type:
                type: string
                maxLength: 1
                pattern: ^\d{1}$
                description: >
                  Tipo de Telefone
                  * `1` - Fixo
                  * `2` - Móvel
              areaCode:
                type: string
                maxLength: 2
                pattern: ^\d{2}$
              number:
                type: string
                maxLength: 10
                pattern: ^([0-9]{4,5})-([0-9]{4})$
          description: Telefone
      required:
        - standard
        - exceptionAvailability
        - allowPublicAccess
    BranchServices:
      type: object
      properties:
        codes:
          type: array
          items:
            type: string
            enum: ["1","2","3","4","5","6","7","8"]
            maxLength: 2
            pattern: ^\d{1,2}$
          description: > 
            Serviços oferecidos pela dependência própria
            * `1` - Abertura de contas
            * `2` - Recebimentos, pagamentos e transferências eletrônicas
            * `3` - Recebimentos e pagamentos de qualquer natureza
            * `4` - Operações de crédito
            * `5` - Cartão de crédito
            * `6` - Operações de câmbio
            * `7` - Investimentos
            * `8` - Seguros
        additionalInfo:
          type: string
          description: Campo aberto para detalhamento
          maxLength: 2000
      required:
        - codes
    EletronicChannel:
      type: object
      properties:
        identification:
          $ref: '#/components/schemas/EletronicChannelIdentification'
        services:
          $ref: '#/components/schemas/EletronicChannelServices'
      required:
        - identification
        - services
    EletronicChannelIdentification:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum: ["1","2","3","4","5","6"]
          maxLength: 2
          pattern: ^\d{1,2}$
          description: >
            Tipo de canal de atendimento eletrônico
            * `1` - Internet banking
            * `2` - Mobile banking
            * `3` - Central telefônica banking
            * `4` - SAC
            * `5` - Ouvidoria
            * `6` - Chat
        phones:
          type: array
          items:
            properties:
              countryCode:
                type: string
                maxLength: 2
                pattern: ^\d{2}$
              areaCode:
                type: string
                maxLength: 2
                pattern: ^\d{2}$
              number:
                type: string
                maxLength: 13
                pattern: ^([0-9]{4,5})-([0-9]{4})$
              additionalInfo:
                type: string
                maxLength: 50
        url:
          type: string
          maxLength: 1024
    EletronicChannelServices:
      type: object
      required:
        - codes
      properties:
        codes:
          type: array
          items:
            type: string
            enum: ["1","2","3","4","5","6","7","8"]
            maxLength: 2
            pattern: ^\d{1,2}$
            description: >
              Serviços oferecidos pelo canal de atendimento eletrônico
              * `1` - Abertura de contas
              * `2` - Recebimentos, pagamentos e transferências eletrônicas
              * `3` - Operações de crédito
              * `4` - Cartão de crédito
              * `5` - Operações de câmbio
              * `6` - Investimentos
              * `7` - Seguros
              * `8` - Atendimento as demandas de cliente
        additionalInfo:
          type: string
          maxLength: 2000
          description: Campo aberto para detalhamento
    PostalAddress:
      type: object
      properties:
        streetType:
          type: string
          description: Tipo de logradouro
          maxLength: 10
          enum: ["Aeroporto", "Alameda", "Área", "Avenida", "Campo", "Chácara", "Colônia", "Condomínio", "Conjunto", "Distrito", "Esplanada", "Estação", "Estrada", "Fazenda", "Feira", "Jardim", "Ladeira", "Lago", "Lagoa", "Largo", "Loteamento", "Núcleo", "Parque", "Passarela", "Pátio", "Praça", "Quadra", "Recanto", "Residencial", "Rodovia", "Rua", "Setor", "Sítio", "Travessa", "Trecho", "Trevo", "Vale", "Vereda", "Via", "Viaduto", "Viela", "Vila"]
        streetName:
          type: string
          description: Nome do logradouro
          maxLength: 50
        buildingNumber:
          type: string
          description: Número
          maxLength: 6
        additionalInfo:
          type: string
          description: Complemento
          maxLength: 30
        districtName:
          type: string
          description: Bairro
          maxLength: 50
        townName:
          type: string
          description: Cidade
          maxLength: 50
        countrySubDivision:
          type: string
          description: Estado
          pattern: ^[A-Z]{2}$
          enum: [AC,AL,AP,AM,BA,CE,DF,ES,GO,MA,MT,MS,MG,PA,PB,PR,PE,PI,RJ,RN,RS,RO,RR,SC,SP,SE,TO]
          maxLength: 2
        postCode:
          type: string
          description: CEP
          pattern: ^\d{5}-\d{3}$
          maxLength: 9
      required: 
        - streetType
        - streetName
        - buildingNumber
        - districtName
        - townName
        - countrySubDivision
        - postCode
    CNPJ:
      type: object
      properties:
        cnpjNumber:
          type: string
          description: CNPJ
          maxLength: 14
      required:
        - cnpjNumber
    Links:
      type: object
      properties:
        self:
          type: string
          description: URL da página atualmente requisitada
        first:
          type: string
          description: URL da primeira página de registros
        prev:
          type: string
          description: URL da página anterior de registros
        next:
          type: string
          description: URL da próxima página de registros
        last:
          type: string
          description: URL da última página de registros
    Meta:
      type: object
      properties:
        totalRecords:
          type: integer
          description: Total de registros encontrados
        totalPages:
          type: integer
          description: Total de páginas para os registros encontrados
      required:
        - totalRecords
        - totalPages